pairs:
  - sample: MPXV_2023_02
    r1: data-example/MPXV_2023_02_R1.fastq
    r2: data-example/MPXV_2023_02_R2.fastq

references:
  mpox: data-example/refs/MPXV.fasta
  vzv: data-example/refs/VZV.fasta

context_acc:
  mpox:
    - data-example/context/mpox_context.fasta
  vzv:
    - data-example/context/vzv_context.fasta

params:
  threads: 4
  min_len_contig: 300
  min_depth_consensus: 10
  min_qual: 20
  use_model_finder: false
  iqtree_model: GTR+G+I
  bootstrap: 1000
  blast_remote: true


kraken2:
  enable: true
  db: /path/to/kraken2-db

kaiju:
  enable: true
  db_fmi: /path/to/kaiju_db.fmi
  nodes: /path/to/nodes.dmp
  names: /path/to/names.dmp
